package gg.vape.mapping;

import gg.vape.wrapper.impl.ForgeVersion;
import pub.nextsense.Tweaker;

public class MappedClasses {
   public static final Class<?> ForgeVersionClass = Tweaker.getClazz("net/minecraftforge/common/ForgeVersion");
   public static final Class<?> Minecraft = Tweaker.getClazz("net/minecraft/client/Minecraft");
   public static final Class<?> Entity = Tweaker.getClazz("net/minecraft/entity/Entity");
   public static final Class<?> EntityPlayer = Tweaker.getClazz("net/minecraft/entity/player/EntityPlayer");
   public static final Class<?> EntityPlayerSP = Tweaker.getClazz("net/minecraft/client/entity/EntityPlayerSP");
   public static final Class<?> GuiScreen = Tweaker.getClazz("net/minecraft/client/gui/GuiScreen");
   public static final Class<?> GuiChat = Tweaker.getClazz("net/minecraft/client/gui/GuiChat");
   public static final Class<?> Session = Tweaker.getClazz("net/minecraft/util/Session");
   public static final Class<?> GameSettings = Tweaker.getClazz("net/minecraft/client/settings/GameSettings");
   public static final Class<?> KeyBinding = Tweaker.getClazz("net/minecraft/client/settings/KeyBinding");
   public static final Class<?> World = Tweaker.getClazz("net/minecraft/world/World");
   public static final Class<?> WorldProvider = Tweaker.getClazz("net/minecraft/world/WorldProvider");
   public static final Class<?> WorldClient = Tweaker.getClazz("net/minecraft/client/multiplayer/WorldClient");
   public static final Class<?> EntityLivingBase = Tweaker.getClazz("net/minecraft/entity/EntityLivingBase");
   public static final Class<?> FontRenderer = Tweaker.getClazz("net/minecraft/client/gui/FontRenderer");
   public static final Class<?> MovementInput = Tweaker.getClazz("net/minecraft/util/MovementInput");
   public static final Class<?> PlayerControllerMP = Tweaker.getClazz("net/minecraft/client/multiplayer/PlayerControllerMP");
   public static final Class<?> EntityRenderer = Tweaker.getClazz("net/minecraft/client/renderer/EntityRenderer");
   public static final Class<?> EntityItemFrame = Tweaker.getClazz("net/minecraft/entity/item/EntityItemFrame");
   public static final Class<?> ScaledResolution = Tweaker.getClazz("net/minecraft/client/gui/ScaledResolution");
   public static final Class<?> InventoryPlayer = Tweaker.getClazz("net/minecraft/entity/player/InventoryPlayer");
   public static final Class<?> ItemStack = Tweaker.getClazz("net/minecraft/item/ItemStack");
   public static final Class<?> Item = Tweaker.getClazz("net/minecraft/item/Item");
   public static final Class<?> ItemPotion = Tweaker.getClazz("net/minecraft/item/ItemPotion");
   public static final Class<?> GuiContainer = Tweaker.getClazz("net/minecraft/client/gui/inventory/GuiContainer");
   public static final Class<?> Slot = Tweaker.getClazz("net/minecraft/inventory/Slot");
   public static final Class<?> Container = Tweaker.getClazz("net/minecraft/inventory/Container");
   public static final Class<?> EntityOtherPlayerMP = Tweaker.getClazz("net/minecraft/client/entity/EntityOtherPlayerMP");
   public static final Class<?> RenderManager = Tweaker.getClazz("net/minecraft/client/renderer/entity/RenderManager");
   public static final Class<?> EntityMob = Tweaker.getClazz("net/minecraft/entity/monster/EntityMob");
   public static final Class<?> EntityAnimal = Tweaker.getClazz("net/minecraft/entity/passive/EntityAnimal");
   public static final Class<?> EntitySlime = Tweaker.getClazz("net/minecraft/entity/monster/EntitySlime");
   public static final Class<?> Block = Tweaker.getClazz("net/minecraft/block/Block");
   public static final Class<?> ItemEnderPearl = Tweaker.getClazz("net/minecraft/item/ItemEnderPearl");
   public static final Class<?> ItemFood = Tweaker.getClazz("net/minecraft/item/ItemFood");
   public static final Class<?> ItemSword = Tweaker.getClazz("net/minecraft/item/ItemSword");
   public static final Class<?> Tessellator = Tweaker.getClazz("net/minecraft/client/renderer/Tessellator");
   public static final Class<?> Event;
   public static final Class<?> EventBus;
   public static final Class<?> MouseEvent = Tweaker.getClazz("net/minecraftforge/client/event/MouseEvent");
   public static final Class<?> MinecraftForge = Tweaker.getClazz("net/minecraftforge/common/MinecraftForge");
   public static final Class<?> TextureManager = Tweaker.getClazz("net/minecraft/client/renderer/texture/TextureManager");
   public static final Class<?> IResourceManager = Tweaker.getClazz("net/minecraft/client/resources/IResourceManager");
   public static final Class<?> Framebuffer = Tweaker.getClazz("net/minecraft/client/shader/Framebuffer");
   public static final Class<?> ResourceLocation = Tweaker.getClazz("net/minecraft/util/ResourceLocation");
   public static final Class<?> ShaderGroup = Tweaker.getClazz("net/minecraft/client/shader/ShaderGroup");
   public static final Class<?> Blocks = Tweaker.getClazz("net/minecraft/init/Blocks");
   public static final Class<?> Material = Tweaker.getClazz("net/minecraft/block/material/Material");
   public static final Class<?> BlockFence = Tweaker.getClazz("net/minecraft/block/BlockFence");
   public static final Class<?> BlockWall = Tweaker.getClazz("net/minecraft/block/BlockWall");
   public static final Class<?> BlockFenceGate = Tweaker.getClazz("net/minecraft/block/BlockFenceGate");
   public static final Class<?> BlockChest = Tweaker.getClazz("net/minecraft/block/BlockChest");
   public static final Class<?> NetHandlerPlayClient = Tweaker.getClazz("net/minecraft/client/network/NetHandlerPlayClient");
   public static final Class<?> Packet = Tweaker.getClazz("net/minecraft/network/Packet");
   public static final Class<?> Potion = Tweaker.getClazz("net/minecraft/potion/Potion");
   public static final Class<?> PotionEffect = Tweaker.getClazz("net/minecraft/potion/PotionEffect");
   public static final Class<?> EntityAmbientCreature = Tweaker.getClazz("net/minecraft/entity/passive/EntityAmbientCreature");
   public static final Class<?> NetworkManager = Tweaker.getClazz("net/minecraft/network/NetworkManager");
   public static final Class<?> Channel = Tweaker.getClazz("io/netty/channel/Channel");
   public static final Class<?> INetHandler = Tweaker.getClazz("net/minecraft/network/INetHandler");
   public static final Class<?> GenericFutureListener = Tweaker.getClazz("io/netty/util/concurrent/GenericFutureListener");
   public static final Class<?> InboundHandlerTuplePacketListener = Tweaker.getClazz("net/minecraft/network/NetworkManager$InboundHandlerTuplePacketListener");
   public static final Class<?> GuiChest = Tweaker.getClazz("net/minecraft/client/gui/inventory/GuiChest");
   public static final Class<?> IInventory = Tweaker.getClazz("net/minecraft/inventory/IInventory");
   public static final Class<?> Timer = Tweaker.getClazz("net/minecraft/util/Timer");
   public static final Class<?> FoodStats = Tweaker.getClazz("net/minecraft/util/FoodStats");
   public static final Class<?> IAttributeInstance = Tweaker.getClazz("net/minecraft/entity/ai/attributes/IAttributeInstance");
   public static final Class<?> AttributeModifier = Tweaker.getClazz("net/minecraft/entity/ai/attributes/AttributeModifier");
   public static final Class<?> IAttribute = Tweaker.getClazz("net/minecraft/entity/ai/attributes/IAttribute");
   public static final Class<?> SharedMonsterAttributes = Tweaker.getClazz("net/minecraft/entity/SharedMonsterAttributes");
   public static final Class<?> ItemAxe = Tweaker.getClazz("net/minecraft/item/ItemAxe");
   public static final Class<?> EntityCreature = Tweaker.getClazz("net/minecraft/entity/EntityCreature");
   public static final Class<?> Team = Tweaker.getClazz("net/minecraft/scoreboard/Team");
   public static final Class<?> GameSettings$Options = Tweaker.getClazz("net/minecraft/client/settings/GameSettings$Options");
   public static final Class<?> RenderGlobal = Tweaker.getClazz("net/minecraft/client/renderer/RenderGlobal");
   public static final Class<?> ItemBlock = Tweaker.getClazz("net/minecraft/item/ItemBlock");
   public static final Class<?> GameProfile = Tweaker.getClazz("com/mojang/authlib/GameProfile");
   public static final Class<?> ItemSnowball = Tweaker.getClazz("net/minecraft/item/ItemSnowball");
   public static final Class<?> ItemEgg = Tweaker.getClazz("net/minecraft/item/ItemEgg");
   public static final Class<?> TileEntity = Tweaker.getClazz("net/minecraft/tileentity/TileEntity");
   public static final Class<?> TileEntityChest = Tweaker.getClazz("net/minecraft/tileentity/TileEntityChest");
   public static final Class<?> TileEntityEnderChest = Tweaker.getClazz("net/minecraft/tileentity/TileEntityEnderChest");
   public static final Class<?> TileEntityMobSpawner = Tweaker.getClazz("net/minecraft/tileentity/TileEntityMobSpawner");
   public static final Class<?> TileEntityHopper = Tweaker.getClazz("net/minecraft/tileentity/TileEntityHopper");
   public static final Class<?> TileEntityFurnace = Tweaker.getClazz("net/minecraft/tileentity/TileEntityFurnace");
   public static final Class<?> TileEntityDropper = Tweaker.getClazz("net/minecraft/tileentity/TileEntityDropper");
   public static final Class<?> TileEntityDispenser = Tweaker.getClazz("net/minecraft/tileentity/TileEntityDispenser");
   public static final Class<?> MobSpawnerBaseLogic = Tweaker.getClazz("net/minecraft/tileentity/MobSpawnerBaseLogic");
   public static final Class<?> IRenderHandler = Tweaker.getClazz("net/minecraftforge/client/IRenderHandler");
   public static final Class<?> RenderBlockOverlayEvent = Tweaker.getClazz("net/minecraftforge/client/event/RenderBlockOverlayEvent");
   public static final Class<?> ItemSoup = Tweaker.getClazz("net/minecraft/item/ItemSoup");
   public static final Class<?> PlayerCapabilities = Tweaker.getClazz("net/minecraft/entity/player/PlayerCapabilities");
   public static final Class<?> ItemArmor = Tweaker.getClazz("net/minecraft/item/ItemArmor");
   public static final Class<?> EnchantmentHelper = Tweaker.getClazz("net/minecraft/enchantment/EnchantmentHelper");
   public static final Class<?> Enchantment = Tweaker.getClazz("net/minecraft/enchantment/Enchantment");
   public static final Class<?> NBTTagList = Tweaker.getClazz("net/minecraft/nbt/NBTTagList");
   public static final Class<?> NBTTagCompound = Tweaker.getClazz("net/minecraft/nbt/NBTTagCompound");
   public static final Class<?> ModelRenderer = Tweaker.getClazz("net/minecraft/client/model/ModelRenderer");
   public static final Class<?> EnumCreatureAttribute = Tweaker.getClazz("net/minecraft/entity/EnumCreatureAttribute");
   public static final Class<?> DamageSource = Tweaker.getClazz("net/minecraft/util/DamageSource");
   public static final Class<?> ItemBow = Tweaker.getClazz("net/minecraft/item/ItemBow");
   public static final Class<?> ItemTool = Tweaker.getClazz("net/minecraft/item/ItemTool");
   public static final Class<?> ItemFishingRod = Tweaker.getClazz("net/minecraft/item/ItemFishingRod");
   public static final Class<?> ItemGlassBottle = Tweaker.getClazz("net/minecraft/item/ItemGlassBottle");
   public static final Class<?> ItemBucket = Tweaker.getClazz("net/minecraft/item/ItemBucket");
   public static final Class<?> ItemAppleGold = Tweaker.getClazz("net/minecraft/item/ItemAppleGold");
   public static final Class<?> ItemPickaxe = Tweaker.getClazz("net/minecraft/item/ItemPickaxe");
   public static final Class<?> ItemSpade = Tweaker.getClazz("net/minecraft/item/ItemSpade");
   public static final Class<?> Items = Tweaker.getClazz("net/minecraft/init/Items");
   public static final Class<?> RenderHelper = Tweaker.getClazz("net/minecraft/client/renderer/RenderHelper");
   public static final Class<?> INetHandlerPlayClient = Tweaker.getClazz("net/minecraft/network/play/INetHandlerPlayClient");
   public static final Class<?> MouseHelper = Tweaker.getClazz("net/minecraft/util/MouseHelper");
   public static final Class<?> Chunk = Tweaker.getClazz("net/minecraft/world/chunk/Chunk");
   public static final Class<?> IChunkProvider = Tweaker.getClazz("net/minecraft/world/chunk/IChunkProvider");
   public static final Class<?> ITextureObject = Tweaker.getClazz("net/minecraft/client/renderer/texture/ITextureObject");
   public static final Class<?> BlockLiquid = Tweaker.getClazz("net/minecraft/block/BlockLiquid");
   public static final Class<?> GuiInventory = Tweaker.getClazz("net/minecraft/client/gui/inventory/GuiInventory");
   public static final Class<?> Render = Tweaker.getClazz("net/minecraft/client/renderer/entity/Render");
   public static final Class<?> ModelBase = Tweaker.getClazz("net/minecraft/client/model/ModelBase");
   public static final Class<?> ModelBiped = Tweaker.getClazz("net/minecraft/client/model/ModelBiped");
   public static final Class<?> RenderPlayer = Tweaker.getClazz("net/minecraft/client/renderer/entity/RenderPlayer");
   public static final Class<?> EntityPotion = Tweaker.getClazz("net/minecraft/entity/projectile/EntityPotion");
   public static final Class<?> EntityFishHook = Tweaker.getClazz("net/minecraft/entity/projectile/EntityFishHook");
   public static final Class<?> EntityArrow = Tweaker.getClazz("net/minecraft/entity/projectile/EntityArrow");
   public static final Class<?> EntityThrowable = Tweaker.getClazz("net/minecraft/entity/projectile/EntityThrowable");
   public static final Class<?> IProjectile = Tweaker.getClazz("net/minecraft/entity/IProjectile");
   public static final Class<?> EntityEnderman = Tweaker.getClazz("net/minecraft/entity/monster/EntityEnderman");
   public static final Class<?> EntitySnowball = Tweaker.getClazz("net/minecraft/entity/projectile/EntitySnowball");
   public static final Class<?> EntityEnderPearl = Tweaker.getClazz("net/minecraft/entity/item/EntityEnderPearl");
   public static final Class<?> EntityEgg = Tweaker.getClazz("net/minecraft/entity/projectile/EntityEgg");
   public static final Class<?> GuiScreenEvent = Tweaker.getClazz("net/minecraftforge/client/event/GuiScreenEvent");
   public static final Class<?> GuiScreenEvent$DrawScreenEvent = Tweaker.getClazz("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent");
   public static final Class<?> GuiScreenEvent$DrawScreenEvent$Pre = Tweaker.getClazz("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Pre");
   public static final Class<?> GuiScreenEvent$DrawScreenEvent$Post = Tweaker.getClazz("net/minecraftforge/client/event/GuiScreenEvent$DrawScreenEvent$Post");
   public static final Class<?> LaunchClassLoader = Tweaker.getClazz("net/minecraft/launchwrapper/LaunchClassLoader");
   public static final Class<?> Launch = Tweaker.getClazz("net/minecraft/launchwrapper/Launch");
   public static final Class<?> ChannelHandlerContext = Tweaker.getClazz("io/netty/channel/ChannelHandlerContext");
   public static final Class<?> ClientChatReceivedEvent = Tweaker.getClazz("net/minecraftforge/client/event/ClientChatReceivedEvent");
   public static final Class<?> Item$ToolMaterial = Tweaker.getClazz("net/minecraft/item/Item$ToolMaterial");
   public static final Class<?> ItemArmor$ArmorMaterial = Tweaker.getClazz("net/minecraft/item/ItemArmor$ArmorMaterial");
   public static final Class<?> RenderLivingEvent = Tweaker.getClazz("net/minecraftforge/client/event/RenderLivingEvent");
   public static final Class<?> TickEvent;
   public static final Class<?> TickEvent$RenderTickEvent;
   public static final Class<?> TickEventPhase;
   public static final Class<?> TickEvent$PlayerTickEvent;
   public static final Class<?> InputEvent$KeyInputEvent;
   public static final Class<?> RenderHandEvent;
   public static Class<?> EntityClientPlayerMP;
   public static Class<?> Vec3i;
   public static Class<?> BlockPos;
   public static Class<?> EnumFacing = Tweaker.getClazz("net/minecraft/util/EnumFacing");
   public static Class<?> IBlockState;
   public static Class<?> CPacketEntityAction$Action;
   public static Class<?> TickEvent$ClientTickEvent;
   public static Class<?> NetworkPlayerInfo;
   public static Class<?> EntityArmorStand;
   public static Class<?> VertexFormat;
   public static Class<?> DefaultVertexFormats;
   public static Class<?> IEntitySelector;
   public static Class<?> ModelPlayer;
   public static Class<?> Vec3d;
   public static Class<?> AxisAlignedBB;
   public static Class<?> RayTraceResult;
   public static Class<?> RayTraceResult$Type;
   public static Class<?> CPacketKeepAlive;
   public static Class<?> CPacketAnimation;
   public static Class<?> CPacketEntityAction;
   public static Class<?> CPacketChatMessage;
   public static Class<?> CPacketUseEntity;
   public static Class<?> CPacketPlayer;
   public static Class<?> CPacketPlayerDigging;
   public static Class<?> CPacketHeldItemChange;
   public static Class<?> RenderItem;
   public static Class<?> CPacketUseEntity$Action;
   public static Class<?> AbstractAttributeMap;
   public static Class<?> ITextComponent;
   public static Class<?> TextComponentString;
   public static Class<?> Style;
   public static Class<?> TextComponentTranslation;
   public static Class<?> BufferBuilder;
   public static Class<?> SPacketExplosion;
   public static Class<?> SPacketEntityVelocity;
   public static Class<?> SPacketEntity;
   public static Class<?> SPacketEntityTeleport;
   public static Class<?> SPacketPlayerPosLook;
   public static Class<?> RenderLivingBase;
   public static Class<?> RegistryNamespaced;
   public static Class<?> RegistrySimple;
   public static Class<?> PlayerInteractEvent$Action;
   public static Class<?> C03PacketPlayer$C05PacketPlayerLook;
   public static Class<?> C03PacketPlayer$C04PacketPlayerPosition;
   public static Class<?> C03PacketPlayer$C06PacketPlayerPosLook;
   public static Class<?> SoundEvent;
   public static Class<?> EnumHand;
   public static Class<?> ClickType;
   public static Class<?> EnumActionResult;
   public static Class<?> NonNullList;
   public static Class<?> EntityEquipmentSlot;
   public static Class<?> PotionUtils;
   public static Class<?> IBlockAccess;
   public static Class<?> ItemSplashPotion;
   public static Class<?> MoverType;
   public static Class<?> EffectRenderer;
   public static Class<?> EntityCritFX;
   public static Class<?> EntityCrit2FX;
   public static String forgePackagePrefix;
   public static String jforgePackagePrefix;

   static {
      if (ForgeVersion.minorVersion() > 13) {
         if (ForgeVersion.minorVersion() >= 23) {
            Vec3i = Tweaker.getClazz("net/minecraft/util/math/Vec3i");
            BlockPos = Tweaker.getClazz("net/minecraft/util/math/BlockPos");
            IBlockState = Tweaker.getClazz("net/minecraft/block/state/IBlockState");
            CPacketEntityAction$Action = Tweaker.getClazz("net/minecraft/network/play/client/CPacketEntityAction$Action");
         } else {
            Vec3i = Tweaker.getClazz("net/minecraft/util/Vec3i");
            BlockPos = Tweaker.getClazz("net/minecraft/util/BlockPos");
            IBlockState = Tweaker.getClazz("net/minecraft/block/state/IBlockState");
            CPacketEntityAction$Action = Tweaker.getClazz("net/minecraft/network/play/client/C0BPacketEntityAction$Action");
         }

         NetworkPlayerInfo = Tweaker.getClazz("net/minecraft/client/network/NetworkPlayerInfo");
         Event = Tweaker.getClazz("net/minecraftforge/fml/common/eventhandler/Event");
         EventBus = Tweaker.getClazz("net/minecraftforge/fml/common/eventhandler/EventBus");
         TickEvent = Tweaker.getClazz("net/minecraftforge/fml/common/gameevent/TickEvent");
         TickEventPhase = Tweaker.getClazz("net/minecraftforge/fml/common/gameevent/TickEvent$Phase");
         TickEvent$RenderTickEvent = Tweaker.getClazz("net/minecraftforge/fml/common/gameevent/TickEvent$RenderTickEvent");
         TickEvent$PlayerTickEvent = Tweaker.getClazz("net/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent");
         InputEvent$KeyInputEvent = Tweaker.getClazz("net/minecraftforge/fml/common/gameevent/InputEvent$KeyInputEvent");
         TickEvent$ClientTickEvent = Tweaker.getClazz("net/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent");
         forgePackagePrefix = "net/minecraftforge/";
         EntityArmorStand = Tweaker.getClazz("net/minecraft/entity/item/EntityArmorStand");
         VertexFormat = Tweaker.getClazz("net/minecraft/client/renderer/vertex/VertexFormat");
         DefaultVertexFormats = Tweaker.getClazz("net/minecraft/client/renderer/vertex/DefaultVertexFormats");
         ModelPlayer = Tweaker.getClazz("net/minecraft/client/model/ModelPlayer");
         IBlockAccess = Tweaker.getClazz("net/minecraft/world/IBlockAccess");
      } else {
         IEntitySelector = Tweaker.getClazz("net/minecraft/command/IEntitySelector");
         Event = Tweaker.getClazz("cpw/mods/fml/common/eventhandler/Event");
         EventBus = Tweaker.getClazz("cpw/mods/fml/common/eventhandler/EventBus");
         TickEvent = Tweaker.getClazz("cpw/mods/fml/common/gameevent/TickEvent");
         TickEventPhase = Tweaker.getClazz("cpw/mods/fml/common/gameevent/TickEvent$Phase");
         TickEvent$PlayerTickEvent = Tweaker.getClazz("cpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent");
         TickEvent$RenderTickEvent = Tweaker.getClazz("cpw/mods/fml/common/gameevent/TickEvent$RenderTickEvent");
         InputEvent$KeyInputEvent = Tweaker.getClazz("cpw/mods/fml/common/gameevent/InputEvent$KeyInputEvent");
         TickEvent$ClientTickEvent = Tweaker.getClazz("cpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent");
         EntityClientPlayerMP = Tweaker.getClazz("net/minecraft/client/entity/EntityClientPlayerMP");
         forgePackagePrefix = "cpw/mods/";
      }

      if (ForgeVersion.minorVersion() >= 23) {
         Vec3d = Tweaker.getClazz("net/minecraft/util/math/Vec3d");
         AxisAlignedBB = Tweaker.getClazz("net/minecraft/util/math/AxisAlignedBB");
         RayTraceResult = Tweaker.getClazz("net/minecraft/util/math/RayTraceResult");
         RayTraceResult$Type = Tweaker.getClazz("net/minecraft/util/math/RayTraceResult$Type");
         CPacketKeepAlive = Tweaker.getClazz("net/minecraft/network/play/client/CPacketKeepAlive");
         CPacketAnimation = Tweaker.getClazz("net/minecraft/network/play/client/CPacketAnimation");
         CPacketEntityAction = Tweaker.getClazz("net/minecraft/network/play/client/CPacketEntityAction");
         CPacketChatMessage = Tweaker.getClazz("net/minecraft/network/play/client/CPacketChatMessage");
         CPacketUseEntity = Tweaker.getClazz("net/minecraft/network/play/client/CPacketUseEntity");
         CPacketPlayer = Tweaker.getClazz("net/minecraft/network/play/client/CPacketPlayer");
         CPacketPlayerDigging = Tweaker.getClazz("net/minecraft/network/play/client/CPacketPlayerDigging");
         CPacketHeldItemChange = Tweaker.getClazz("net/minecraft/network/play/client/CPacketHeldItemChange");
         RenderItem = Tweaker.getClazz("net/minecraft/client/renderer/RenderItem");
         CPacketUseEntity$Action = Tweaker.getClazz("net/minecraft/network/play/client/CPacketUseEntity$Action");
         AbstractAttributeMap = Tweaker.getClazz("net/minecraft/entity/ai/attributes/AbstractAttributeMap");
         ITextComponent = Tweaker.getClazz("net/minecraft/util/text/ITextComponent");
         TextComponentString = Tweaker.getClazz("net/minecraft/util/text/TextComponentString");
         Style = Tweaker.getClazz("net/minecraft/util/text/Style");
         TextComponentTranslation = Tweaker.getClazz("net/minecraft/util/text/TextComponentTranslation");
         BufferBuilder = Tweaker.getClazz("net/minecraft/client/renderer/BufferBuilder");
         SPacketExplosion = Tweaker.getClazz("net/minecraft/network/play/server/SPacketExplosion");
         SPacketEntityVelocity = Tweaker.getClazz("net/minecraft/network/play/server/SPacketEntityVelocity");
         SPacketEntity = Tweaker.getClazz("net/minecraft/network/play/server/SPacketEntity");
         SPacketEntityTeleport = Tweaker.getClazz("net/minecraft/network/play/server/SPacketEntityTeleport");
         SPacketPlayerPosLook = Tweaker.getClazz("net/minecraft/network/play/server/SPacketPlayerPosLook");
         RenderLivingBase = Tweaker.getClazz("net/minecraft/client/renderer/entity/RenderLivingBase");
         RegistryNamespaced = Tweaker.getClazz("net/minecraft/util/registry/RegistryNamespaced");
         RegistrySimple = Tweaker.getClazz("net/minecraft/util/registry/RegistrySimple");
         C03PacketPlayer$C05PacketPlayerLook = Tweaker.getClazz("net/minecraft/network/play/client/CPacketPlayer$Rotation");
         C03PacketPlayer$C04PacketPlayerPosition = Tweaker.getClazz("net/minecraft/network/play/client/CPacketPlayer$Position");
         C03PacketPlayer$C06PacketPlayerPosLook = Tweaker.getClazz("net/minecraft/network/play/client/CPacketPlayer$PositionRotation");
         MoverType = Tweaker.getClazz("net/minecraft/entity/MoverType");
         SoundEvent = Tweaker.getClazz("net/minecraft/util/SoundEvent");
         EnumHand = Tweaker.getClazz("net/minecraft/util/EnumHand");
         ClickType = Tweaker.getClazz("net/minecraft/inventory/ClickType");
         EnumActionResult = Tweaker.getClazz("net/minecraft/util/EnumActionResult");
         NonNullList = Tweaker.getClazz("net/minecraft/util/NonNullList");
         EntityEquipmentSlot = Tweaker.getClazz("net/minecraft/inventory/EntityEquipmentSlot");
         PotionUtils = Tweaker.getClazz("net/minecraft/potion/PotionUtils");
         ItemSplashPotion = Tweaker.getClazz("net/minecraft/item/ItemSplashPotion");
      } else {
         Vec3d = Tweaker.getClazz("net/minecraft/util/Vec3");
         AxisAlignedBB = Tweaker.getClazz("net/minecraft/util/AxisAlignedBB");
         RayTraceResult = Tweaker.getClazz("net/minecraft/util/MovingObjectPosition");
         RayTraceResult$Type = Tweaker.getClazz("net/minecraft/util/MovingObjectPosition$MovingObjectType");
         CPacketKeepAlive = Tweaker.getClazz("net/minecraft/network/play/client/C00PacketKeepAlive");
         CPacketAnimation = Tweaker.getClazz("net/minecraft/network/play/client/C0APacketAnimation");
         CPacketEntityAction = Tweaker.getClazz("net/minecraft/network/play/client/C0BPacketEntityAction");
         CPacketChatMessage = Tweaker.getClazz("net/minecraft/network/play/client/C01PacketChatMessage");
         CPacketUseEntity = Tweaker.getClazz("net/minecraft/network/play/client/C02PacketUseEntity");
         CPacketPlayer = Tweaker.getClazz("net/minecraft/network/play/client/C03PacketPlayer");
         CPacketPlayerDigging = Tweaker.getClazz("net/minecraft/network/play/client/C07PacketPlayerDigging");
         CPacketHeldItemChange = Tweaker.getClazz("net/minecraft/network/play/client/C09PacketHeldItemChange");
         RenderItem = Tweaker.getClazz("net/minecraft/client/renderer/entity/RenderItem");
         CPacketUseEntity$Action = Tweaker.getClazz("net/minecraft/network/play/client/C02PacketUseEntity$Action");
         AbstractAttributeMap = Tweaker.getClazz("net/minecraft/entity/ai/attributes/BaseAttributeMap");
         ITextComponent = Tweaker.getClazz("net/minecraft/util/IChatComponent");
         TextComponentString = Tweaker.getClazz("net/minecraft/util/ChatComponentText");
         Style = Tweaker.getClazz("net/minecraft/util/ChatComponentStyle");
         TextComponentTranslation = Tweaker.getClazz("net/minecraft/util/ChatComponentTranslation");
         BufferBuilder = Tweaker.getClazz("net/minecraft/client/renderer/WorldRenderer");
         SPacketExplosion = Tweaker.getClazz("net/minecraft/network/play/server/S27PacketExplosion");
         SPacketEntityVelocity = Tweaker.getClazz("net/minecraft/network/play/server/S12PacketEntityVelocity");
         SPacketEntity = Tweaker.getClazz("net/minecraft/network/play/server/S14PacketEntity");
         SPacketEntityTeleport = Tweaker.getClazz("net/minecraft/network/play/server/S18PacketEntityTeleport");
         SPacketPlayerPosLook = Tweaker.getClazz("net/minecraft/network/play/server/S08PacketPlayerPosLook");
         RenderLivingBase = Tweaker.getClazz("net/minecraft/client/renderer/entity/RendererLivingEntity");
         RegistryNamespaced = Tweaker.getClazz("net/minecraft/util/RegistryNamespaced");
         RegistrySimple = Tweaker.getClazz("net/minecraft/util/RegistrySimple");
         PlayerInteractEvent$Action = Tweaker.getClazz("net/minecraftforge/event/entity/player/PlayerInteractEvent$Action");
         C03PacketPlayer$C05PacketPlayerLook = Tweaker.getClazz("net/minecraft/network/play/client/C03PacketPlayer$C05PacketPlayerLook");
         C03PacketPlayer$C04PacketPlayerPosition = Tweaker.getClazz("net/minecraft/network/play/client/C03PacketPlayer$C04PacketPlayerPosition");
         C03PacketPlayer$C06PacketPlayerPosLook = Tweaker.getClazz("net/minecraft/network/play/client/C03PacketPlayer$C06PacketPlayerPosLook");
         EffectRenderer = Tweaker.getClazz("net/minecraft/client/particle/EffectRenderer");
         EntityCritFX = Tweaker.getClazz("net/minecraft/client/particle/EntityCritFX");
         EntityCrit2FX = Tweaker.getClazz("net/minecraft/client/particle/EntityCrit2FX");
      }

      RenderHandEvent = Tweaker.getClazz("net/minecraftforge/client/event/RenderHandEvent");
      jforgePackagePrefix = forgePackagePrefix.replace("/", ".");
   }
}
